### ISSUE TITLE
Repo listing should show grouping or directory structure and distinguish repos based on their path

### ISSUE THREAD

**Issue by tuukkamustonen** [nosarthur/gita#178] opened 2021-09-01 09:10 UTC
Given structure of:

```
.
project1/project1-repo
project2/project2-repoA
project2/project2-repoB
```

With `gita add -a .`, `gita ll` shows:

```
project1-repo  master      ()
project2-repoA master      ()
project2-repoB master      ()
```

Why not show the groups in that listing, like:

```
project1
    project1-repo  master      ()
project2
    project2-repoA master      ()
    project2-repoB master      ()
```

Or follow directory structure:

```
project1/project1-repo  master      ()
project2/project2-repoA master      ()
project2/project2-repoB master      ()
```

With the flat structure, it's unclear which repo exists and where.

Consider adding:

```
project1/somelib
project2/somelib
```

After `git add -a .`, `gita ll` shows:

```
project1-repo   master      ()
project2-repoA  master      ()
project2-repoB  master      ()
somelib/somelib master      ()
```

Now I don't know why it shows `somelib/somelib` instead of just `somelib`? But it seems to not be aware of the 2 different repos with the same name.

**Comment by tuukkamustonen** [comment] 2021-09-01 17:07
I see you just closed this with a fix (for the duplicate).

Still, about the listing of the repos, I see the problem with groups that you mention. But yeah, if a repo belongs to multiple groups, then it does, and showing it multiple times won't necessarily/probably hurt. So `gita ll -g` could indeed make sense.

Or how about following directory structure per default?

**Comment by tuukkamustonen** [comment] 2021-09-01 17:15
Also `0.15.4` shows something like:

```
$ gita ll
project1-repo    master      ()
project1/somelib master      ()
project2-repoA   master      ()
project2-repoB   master      ()
project2/somelib master      ()
temp             master _    ()
```

Why `-` for some, `/` for the duplicate repos? Isn't it a bit confusing.

As `/` is often understood as hierarchical separator, I think it would indeed be better here.

**Comment by nosarthur** [comment] 2021-09-01 17:23
Please file a separate case for the `gita ll` showing group name

> Why - for some, / for the duplicate repos? Isn't it a bit confusing.

Currently the new repo name defaults to the basename of the repo path, e.g., `somelib`. But if name clash occurs either with respect to existing repo names or other new repo names, its parent directory'name will be added with a `/`. This is not a complete fix but works most of the time. 

Thus in your example, `project2-repoA` is due to your choice, `project2/somelib` is due to the name fix for name clash 

The latest version is v0.15.4.1 by the way.

**Comment by tuukkamustonen** [comment] 2021-09-01 18:32
0.15.4:

```
$ gita add -m .
...
$ gita ll
project1-repo    master      ()
project1/somelib master      ()
project2-repoA   master      ()
project2-repoB   master      ()
project2/somelib master      ()
temp             master _    ()
```

0.15.4.1:

```
$ gita add -m .
$ gita ll
project1-repo   master      ()
project2-repoA  master      ()
project2-repoB  master      ()
somelib/somelib master      ()
temp            master _    ()
...

Seems like the duplicate detector got broken again, a regression?

---

> Currently the new repo name defaults to the basename of the repo path, e.g., somelib for /a/b/c/somelib. But if name clash occurs either with respect to existing repo names or other new repo names, its parent directory'name will be added with a /, e.g., c/somelib. This is not a complete fix but works most of the time.

You're perfectly correct in there about the naming, I temporarily forgot that _I_ named the directory `project1-repo` etc. 😄 So yeah, the dash doesn't come from `gita`, my bad.

Then again, while I understand the potential convenience in adding parent directory only if there's need but it's also confusing (at least for the newcomer) if some entries have the parent dir included, and some don't.

But I'll open a new ticket, I'll think about grouping a bit 👍🏻.

**Comment by nosarthur** [comment] 2021-09-01 23:15
> Then again, while I understand the potential convenience in adding parent directory only if there's need but it's also confusing (at least for the newcomer) if some entries have the parent dir included, and some don't.

You can also run `gita rename <old-repo-name> <new-name>` afterwards

> Seems like the duplicate detector got broken again, a regression?

0.15.4.1 seems to be working on my MBP. What is your machine environment? You wrote `$ gita add -m .`, do you actually mean `$ gita add -a .`?

**Comment by nosarthur** [comment] 2021-09-01 23:23
@tuukkamustonen Please delete your `~/.config/gita/repos.csv` and try `gita add -a .` again with 0.15.4.2. 

Let me know if the duplicate problem still exists

**Comment by tuukkamustonen** [comment] 2021-09-02 05:38
0.15.6 and structure of:

```
temp/
    project1/
        repoA
    project2/
        repoA
        repoB
```

`gita add -a .` works:

```
$ cd temp
$ rm -rf ~/.config/gita .gita/
$ gita add -a .
Found 4 new repo(s).
Created 3 new group(s).
$ gita ll
project1/repoA master      ()
project2/repoA master      ()
repoB          master      ()
temp           master _    ()
```

But `gita add -m .` bugs:

```
$ rm -rf ~/.config/gita .gita/
$ gita add -m .
Found 1 new repo(s).
Inside main repo: temp
Found 4 new repo(s).
$ gita ll
repoA/repoA master      ()
repoB       master      ()
temp        master _    ()
```

This one's a bugging a bit.

**Comment by nosarthur** [comment] 2021-09-02 13:06
It seems `-m` has the same issue, which was caused by whether the path name contains trailing `/`. I could either fix this trailing `/` or just get rid of the `-m` option. Kinda leaning towards the latter

**Comment by tuukkamustonen** [comment] 2021-09-02 14:12
I think `-m` is just confusingly named. It should be `-l` as in (local) or something like that. When inside a local configuration, only show what local config has, when outside a local configuration, show global stuff.

- `gita add .` to (recursively) add all repos within local directory
- `gita add -a .` to also auto-group
- `gita add -l .` to create a local config instead (`.gita/`)
- `gita add -a -l .` to also auto-group

`gita context` could then work so that it only considers local entries when your inside local config, and global entries when your outisde. You wouldn't need `auto` mode? If you need to command also global entries from inside local config directory, just `cd ..` out of it first, open another shell window, etc (shouldn't hurt much).

But maybe it's easier to re-consider that once `ll` works everywhere (it's now slightly bugged, so it's hard to tell what's intentional).

(And hey, sorry for the bloat of tickets and comments! Just had some difficulties in setting it up, so I thought better to speak out than succumb into darkness and completely skip this promising tool! 😅 Thanks for making it OSS!)

**Comment by nosarthur** [comment] 2021-09-03 02:42
It's great to see your tickets and comments! I never used the `-a` and `-m` options for real 😳 and the users who requested them never complained. Maybe no one really uses them

My current plan is to get rid of the `-m` option and make `gita ll` work correctly with the `auto` context. We can start from there and see what to do further

Close this for now and we can continue to discuss in #179

**Closed by nosarthur** 2021-09-03 02:42 UTC
