### ISSUE TITLE
problem displaying repo status properly

### ISSUE THREAD

**Issue by jave** [nosarthur/gita#240] opened 2023-05-17 23:58 UTC
Hello,

I have an odd problem displaying repo status properly.

I run "gita ll" several times after each other.
each run status is reported randomly for different repositories, that is, the status color changes from green to white, to back again.

This of course makes the functionality unusable, so I suspect something fundamentally wrong in my local setup, but I cant figure out what.

Any debugging help would be appreciated. Im sorry for the vagueness in the report, but its a really odd problem.

Some more info:

Python 3.10.11

The repos I try to work with are from: gitlab.com/arbetsformedlingen, a group of about 400 repos. They where initially cloned with Ghorg.

I run gita in an emacs shell buffer, but the problem is the same in a terminal.

**Comment by nosarthur** [comment] 2023-05-18 01:19
what gita version are you using?

do u run `gita ll` literally back to back while the repos are not updating? is color the only difference from run to run? what is the correct status if you determine if with raw git command?

**Comment by jave** [comment] 2023-05-18 12:46
gita 0.16.3 installed with pip yesterday

color differs to from run to run, but also the * status for some repos

the repos are not uppdating

heres status of one repo:

```
14:43:30-joakim@tanaka:~/jobtech/arbetsformedlingen/devops/calamari-build-and-testing-cluster-roadmap$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   readme.org

no changes added to commit (use "git add" and/or "git commit -a")
```
atm gita ll reports it as

```
calamari-build-and-testing-cluster-roadmap                                                                main       update (14 timmar sedan)
```

status in green


this is so strange Im thinking a problem in dependencies or something? 
do you have a working docker container or the like, I could compare with?

**Comment by jave** [comment] 2023-05-18 12:52
example:

```
14:50:07-joakim@tanaka:~/jobtech/arbetsformedlingen/devops/calamari-build-and-testing-cluster-roadmap$ gita ll |grep calamari-build-and-testing-cluster-roadmap
calamari-build-and-testing-cluster-roadmap                                                                main       update (14 hours ago)
14:50:56-joakim@tanaka:~/jobtech/arbetsformedlingen/devops/calamari-build-and-testing-cluster-roadmap$ gita ll |grep calamari-build-and-testing-cluster-roadmap
calamari-build-and-testing-cluster-roadmap                                                                main       update (14 hours ago)
14:51:05-joakim@tanaka:~/jobtech/arbetsformedlingen/devops/calamari-build-and-testing-cluster-roadmap$ gita ll |grep calamari-build-and-testing-cluster-roadmap
calamari-build-and-testing-cluster-roadmap                                                                main *     update (14 hours ago)
```

so the asterisk shows up in the 3rd run, but nothing happened with the repo in between.

**Comment by nosarthur** [comment] 2023-05-18 13:21
could you try 0.16.2.4 and see if the problem persists?

0.16.3 contains an optimization with threadpool #238 I wonder if that causes any race conditions

**Comment by nosarthur** [comment] 2023-05-18 13:23
Actually I can reproduce your problem with 0.16.3 locally with my own repos (only about 10 of them) and it doesn't exist in 0.16.2.4

**Comment by jave** [comment] 2023-05-18 18:08
Do you mean I should try commit 63894703d53b30034161ef81171724bd2f3c9503? The one before the threadool commit? I cant find a 0.16.2.4 tag.

**Comment by nosarthur** [comment] 2023-05-18 20:05
you can do either `pip3 install  gita==0.16.2.4` or `python3 -m pip install  gita==0.16.2.4` with the right python installation, depending on how your python is installed

**Comment by nosarthur** [comment] 2023-05-19 04:30
I know what the problem is. To get the repo information, I changed directory in a bad way. It should be done in the subprocess call via `cwd`

https://github.com/nosarthur/gita/blob/master/gita/info.py#L203

**Comment by nosarthur** [comment] 2023-05-19 04:53
@jave it should be fixed if you update gita to 0.16.3.1

thanks for reporting, I will close the case after fixing the unit tests

**Closed** 2023-05-19 05:10 UTC
Labels: bug

**Comment by jave** [comment] 2023-05-19 09:43
I think the problem with "white" repos are on my end. Ghorg cloned a bunch of repos in our org that where empty, and these get the color white.

**Comment by nosarthur** [comment] 2023-05-19 12:21
let me know if you find anything that doesn't make sense

you can always compare to 0.16.2.4 which should give the correct result
